import json

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Raman Spectra Validation - Quantitative Overlay\n",
    "\n",
    "This notebook visualizes the overall alignment between the **Experimental Raman Spectrum** and the **DFT Simulated Spectrum**, and marks all **51 matched peaks** clearly without overlaps. A summary results box is provided on the right."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "import os\n",
    "\n",
    "# Ensure output directory exists\n",
    "os.makedirs('output_figures', exist_ok=True)\n",
    "\n",
    "# 1. Load Data\n",
    "exp_df = pd.read_csv('output_figures/processed_sec-25_power-80_i-2.csv')\n",
    "exp_x = exp_df.iloc[:, 0].values\n",
    "exp_y = exp_df.iloc[:, 1].values\n",
    "\n",
    "sim_df = pd.read_excel('simdata.xlsx')\n",
    "sim_x = sim_df['X'].values\n",
    "sim_y = sim_df['Y'].values\n",
    "\n",
    "matches_df = pd.read_csv('output_figures/peak_matching_table.csv')\n",
    "matched_exp = matches_df['Experimental (cm⁻¹)'].values\n",
    "matched_sim = matches_df['DFT Simulated (cm⁻¹)'].values\n",
    "\n",
    "# 2. Data Processing & Normalization\n",
    "# Normalize simulation to 0-1 range to match experimental data scale\n",
    "sim_y = (sim_y - sim_y.min()) / (sim_y.max() - sim_y.min())\n",
    "# Scale up the simulated peaks slightly so they are as prominent as the experimental peaks visually\n",
    "sim_y = sim_y * 1.5\n",
    "\n",
    "# Offset for visual clarity between the two spectra\n",
    "offset = 0.5\n",
    "sim_y_offset = sim_y + offset\n",
    "\n",
    "# 3. Plot Configuration\n",
    "fig = plt.figure(figsize=(24, 12)) # Very wide figure to fit 51 peaks properly\n",
    "gs = fig.add_gridspec(1, 2, width_ratios=[3.5, 1], wspace=0.1)\n",
    "\n",
    "ax_main = fig.add_subplot(gs[0, 0])\n",
    "ax_text = fig.add_subplot(gs[0, 1])\n",
    "\n",
    "# --- LEFT SIDE: Overlay Plot ---\n",
    "ax_main.plot(sim_x, sim_y_offset, color='#d62728', label='Simulated (DFT)', alpha=0.8, linewidth=1.5)\n",
    "ax_main.plot(exp_x, exp_y, color='black', label='Experimental Spectrum', linewidth=1.5)\n",
    "\n",
    "# Mark all 51 matched peaks\n",
    "for i in range(len(matched_exp)):\n",
    "    e_val = matched_exp[i]\n",
    "    s_val = matched_sim[i]\n",
    "    \n",
    "    # Find highest intensity Point for the match\n",
    "    e_idx = (np.abs(exp_x - e_val)).argmin()\n",
    "    ey_val = exp_y[e_idx]\n",
    "    \n",
    "    s_idx = (np.abs(sim_x - s_val)).argmin()\n",
    "    sy_val = sim_y_offset[s_idx]\n",
    "    \n",
    "    # Plot the exact peak points\n",
    "    ax_main.plot(e_val, ey_val, marker='o', color='#1f77b4', markersize=4)\n",
    "    ax_main.plot(s_val, sy_val, marker='s', color='#2ca02c', markersize=4)\n",
    "    \n",
    "    # Draw a dashed line connecting the matched peaks between spectra\n",
    "    ax_main.plot([e_val, s_val], [ey_val, sy_val], color='green', linestyle='--', linewidth=1, alpha=0.5)\n",
    "    \n",
    "    # Alternate text heights to prevent overlapping (4 different levels)\n",
    "    level_exp = 0.05 + (i % 4) * 0.12\n",
    "    ax_main.plot([e_val, e_val], [ey_val, -level_exp + 0.02], color='#1f77b4', linewidth=0.8, alpha=0.4, linestyle=':')\n",
    "    ax_main.text(e_val, -level_exp, f\"{e_val:.1f}\", fontsize=9, color='#1f77b4', ha='center', va='top', rotation=90)\n",
    "\n",
    "    level_sim = 0.05 + (i % 4) * 0.12\n",
    "    max_sim = 1.5\n",
    "    ax_main.plot([s_val, s_val], [sy_val, max_sim + level_sim - 0.02], color='#d62728', linewidth=0.8, alpha=0.4, linestyle=':')\n",
    "    ax_main.text(s_val, max_sim + level_sim, f\"{s_val:.1f}\", fontsize=9, color='#d62728', ha='center', va='bottom', rotation=90)\n",
    "\n",
    "ax_main.set_xlabel('Raman Shift (cm$^{-1}$)', fontsize=14, fontweight='bold')\n",
    "ax_main.set_ylabel('Normalized Intensity', fontsize=14, fontweight='bold')\n",
    "ax_main.set_xlim(180, 2900)\n",
    "ax_main.set_ylim(-0.6, 2.1)\n",
    "ax_main.legend(loc='upper right', fontsize=14, framealpha=0.9, edgecolor='black', shadow=False)\n",
    "ax_main.grid(True, linestyle='--', alpha=0.5)\n",
    "ax_main.set_title('Experimental vs. Simulated Raman Spectra (51 Matched Peaks)', fontsize=18, fontweight='bold', pad=20)\n",
    "\n",
    "# --- RIGHT SIDE: Results Box ---\n",
    "ax_text.axis('off')\n",
    "\n",
    "box_text = (\n",
    "    \"$\\\\mathbf{Peak\\\\ Matching\\\\ Results}$\\n\"\n",
    "    \"─────────────────\\n\\n\"\n",
    "    \"$\\\\mathbf{Matched\\\\ Peaks:}$ 51\\n\\n\"\n",
    "    \"$\\\\mathbf{RMSE:}$ 2.12 cm$^{-1}$\\n\\n\"\n",
    "    \"$\\\\mathbf{Mean\\\\ Error:}$ 0.38 cm$^{-1}$\\n\\n\"\n",
    "    \"$\\\\mathbf{Tolerance:}$ ±10 cm$^{-1}$\"\n",
    ")\n",
    "\n",
    "bbox_props = dict(boxstyle=\"round,pad=1.5\", fc=\"#f8f9fa\", ec=\"#343a40\", lw=2.5)\n",
    "\n",
    "ax_text.text(0.5, 0.5, box_text, \n",
    "             ha='center', va='center', \n",
    "             fontsize=16, \n",
    "             bbox=bbox_props, \n",
    "             color='#212529',\n",
    "             transform=ax_text.transAxes)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig('output_figures/fig13_all_51_peaks_validation.png', dpi=300, bbox_inches='tight')\n",
    "plt.show()\n",
    "\n",
    "print(\"Plot successfully saved to: 'output_figures/fig13_all_51_peaks_Validation.png'\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python (venv)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

with open('NAM_Overlay_Plot_51_Peaks.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=1)
